version: "3.9"

services:

  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      - WEBSOCKET_PLUGIN_AUTH_KEY=${PLUGIN_KEY}
      - WEBSOCKET_WEB_AUTH_KEY=${CLIENT_KEY}
    volumes:
      - ../server:/app
      - /app/node_modules

  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: client
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      - WEBSOCKET_URL=https://${DOMAIN}:${SERVER_PORT}
      - WEBSOCKET_KEY=${CLIENT_KEY}
      - NEXTAUTH_URL=https://${DOMAIN}:${CLIENT_PORT}
      - NEXTAUTH_SECRET=${SECRET_KEY}
      - TURN_URL=turn:${DOMAIN}:3434
      - TURN_USERNAME=melodymine
      - TURN_PASSWORD=melodymine
    volumes:
      - ../client:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - server

  coturn:
    image: coturn/coturn
    container_name: coturn
    restart: unless-stopped
    volumes:
      - ./turnserver.conf:/etc/turnserver.conf
    ports:
      - '3477:3477'
      - '3477:3477/udp'

  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx
    ports:
      - '${CLIENT_PORT}:3000'
      - '${SERVER_PORT}:4000'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - server
      - client

  nginx_ssl:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx_ssl
    ports:
      - '80:80'
    volumes:
      - ./nginx-ssl.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot


  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email melody@melody.com -d ${DOMAIN} --agree-tos
    depends_on:
      - nginx_ssl
